const menu = {
    list() {
        return [
    {
        "backMenu":[
            {"buttons":[
                    "查看",
                    "新增",
                    "修改",
                    "删除"
                ],
                "menu":"公告信息管理",
                "menuJump":"列表",
                "tableName":"news"
            }
            ,{"buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "订单",
                            "删除"
                        ],
                        "menu":"任务信息管理",
                        "menuJump":"列表",
                        "tableName":"task"
            }
            ,{"buttons":[
                            "查看",
                    "新增",
                    "修改",
                            "删除"
                        ],
                        "menu":"订单信息管理",
                        "menuJump":"列表",
                        "tableName":"orderreceiving"
            }
            ,{"buttons":[
                    "查看",
                    "新增",
                    "删除",
                    "修改"
                ],
                "menu":"投诉类型管理",
                "menuJump":"列表",
                "tableName":"dictionaryComplaint"
            }
            ,{"buttons":[
                            "查看",
                            "审核",
                        ],
                        "menu":"投诉信息管理",
                        "menuJump":"列表",
                        "tableName":"complaint"
            }
            ,{"buttons":[
                    "查看",
                    "新增",
                    "修改",
                    "删除"
                ],
                "menu":"管理员管理",
                "menuJump":"列表",
                "tableName":"users"
            }
            ,{"buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
            }
            ,{"buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"跑腿管理",
                        "menuJump":"列表",
                        "tableName":"errands"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
            {"buttons":[
                    "查看"
                ],
                "menu":"公告",
                "menuJump":"列表",
                "tableName":"news"
            },
            {"buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"任务信息管理",
                        "menuJump":"列表",
                        "tableName":"task"
            },
            {"buttons":[
                            "查看",
                            "状态"
                        ],
                        "menu":"订单信息管理",
                        "menuJump":"列表",
                        "tableName":"orderreceiving"
            },
            {"buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"投诉信息管理",
                        "menuJump":"列表",
                        "tableName":"complaint"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    },
    {
        "backMenu":[
            {"buttons":[
                    "查看"
                ],
                "menu":"公告",
                "menuJump":"列表",
                "tableName":"news"
            },
            {"buttons":[
                            "查看",
                            "接单"
                        ],
                        "menu":"任务信息管理",
                        "menuJump":"列表",
                        "tableName":"task"
            },
            {"buttons":[
                            "查看",
                            "状态"
                        ],
                        "menu":"订单信息管理",
                        "menuJump":"列表",
                        "tableName":"orderreceiving"
            },
            {"buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"投诉信息管理",
                        "menuJump":"列表",
                        "tableName":"complaint"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"跑腿",
        "tableName":"errands"
    }

]
    }
}
export default menu;
